### ISSUE TITLE
When will the datasets be released

### ISSUE THREAD

**Issue by wangtss** [zju3dv/Mirrored-Human#2]

**Comment by chingswy** [comment]
Hello, thanks for your attention. We will release our dataset as soon as possible. You can take a preview [here](https://chingswy.github.io/Dataset-Demo/mirror-new.html).

**Comment by wangtss** [comment]
> Hello, thanks for your attention. We will release our dataset as soon as possible. You can take a preview [here](https://chingswy.github.io/Dataset-Demo/mirror-new.html).

**Comment by isarandi** [comment]
Hi! Has the whole dataset been released already?
