### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/models/smpl_mean_params.npz'

### ISSUE THREAD

**Issue by shaheen69-wq** [zju3dv/Mirrored-Human#3]
FileNotFoundError: [Errno 2] No such file or directory: 'data/models/smpl_mean_params.npz' 

Where can I find the download link?

**Comment by raypine** [comment]
You can follow this [link](https://github.com/zju3dv/EasyMocap/blob/master/doc/installation.md#02-optional-spin-model).

**Comment by shaheen69-wq** [comment]
Thank you, do you have an idea of ​​how to use two videos as a mirror?

**Comment by chingswy** [comment]
Do you mean human in the two videos perform the same action?

**Comment by shaheen69-wq** [comment]
No, same video, but I flip it

**Comment by chingswy** [comment]
I have no idea.
