### ISSUE TITLE
The scripts for pose reconstructions are missing

### ISSUE THREAD

**Issue by VoidLLY** [zju3dv/Mirrored-Human#4]
Hi, I tried to download the zju-m-test.zip but only zju-m-demo.zip could be found via the link you provided. Did you delete all the scripts folders? Will you release them again in the future? I really appreciate your work. And I'm doing research in a similar area. Thank you.

**Comment by raypine** [comment]
Do you mean [EasyMocap](https://github.com/zju3dv/EasyMocap) ?

**Comment by VoidLLY** [comment]
> Do you mean [EasyMocap](https://github.com/zju3dv/EasyMocap) ?

Just the mirrored_human.

**Comment by raypine** [comment]
The data for demo is at zju-m-demo.zip while the code is at [EasyMocap](https://github.com/zju3dv/EasyMocap).

**Comment by VoidLLY** [comment]
> The data for demo is at zju-m-demo.zip while the code is at [EasyMocap](https://github.com/zju3dv/EasyMocap).

I find it. Many thanks.
