### ISSUE TITLE
关于使用mirrored-human-base数据集进行训练的问题

### ISSUE THREAD

**Issue by XiaoYuhao** [zju3dv/Mirrored-Human#6]
你好，我想使用mirrored-human-base数据集和human3.6m数据集一起训练模型以提高性能，但是发现mirrored-human-base数据集与human3.6m数据集的关键点标注不一样，比如mirrored数据集3d关键点标注有25个，而human3.6m只有17个。请问需要如何处理这个问题呢？

**Comment by chingswy** [comment]
我们只使用了两个数据集中公共的点，可以参考[SPIN](https://github.com/nkolot/SPIN) 中对多个数据集的处理。
