### ISSUE TITLE
there is something wrong with# Run demo on videos python3 apps/demo/1v1p_mirror.py ${data} --out ${out} --vis_smpl --video

### ISSUE THREAD

**Issue by daoboke** [zju3dv/Mirrored-Human#7]

**Comment by daoboke** [comment]
nothing,i solved

**Comment by daoboke** [comment]
> _No description provided._

**Comment by QiFuChina** [comment]
I got same error like below
(easymocap) C:\ResourceCode\EasyMocap>python apps/demo/1v1p_mirror.py data/zju-m-demo --out data/zju-m-demo-output --vis_smpl --video
Traceback (most recent call last):
  File "apps/demo/1v1p_mirror.py", line 8, in <module>
    from easymocap.estimator import SPIN, init_with_spin
ImportError: cannot import name 'init_with_spin'
I try to traceback file` lvlp_mirror.py` but I didn't know where is the model `init_with_spin`

**Comment by daoboke** [comment]
# apps/demo/1v1p_mirror.py
from operator import imod
import numpy as np
from tqdm import tqdm
from os.path import join
from easymocap.dataset.mv1pmf_mirror import ImageFolderMirror as ImageFolder
from easymocap.mytools import Timer
from easymocap.smplmodel import load_model, merge_params, select_nf
from easymocap.estimator.SPIN import SPIN, init_with_spin
from easymocap.pipeline.mirror import multi_stage_optimize
